#!/usr/bin/env python3
"""robots.txt 와 sitemap.xml 을 만든다.

페이지를 추가하거나 지웠으면 다시 돌리면 된다. lastmod 는 각 파일의 git 최종
커밋 시각을 쓴다 — 파일 mtime 은 clone 할 때마다 바뀌어서 의미가 없다.

    python scripts/build_seo.py
"""

from __future__ import annotations

import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from xml.sax.saxutils import escape

ROOT = Path(__file__).resolve().parents[1]
SITE = "https://worldearthquakelabs.com"

# 색인시킬 페이지: (파일, 주소, changefreq, priority). 콘솔이 iframe 으로 부를 때
# 붙는 ?embed=1 사본은 각 페이지의 canonical 이 여기 있는 주소로 넘겨준다. 주소는
# 호스팅이 서빙하는 확장자 없는 형태 -- /map.html 은 /map 으로 308 리다이렉트되므로
# 사이트맵에는 최종 주소만 적는다.
PAGES = [
    ("index.html", "/", "daily", "1.0"),
    ("map.html", "/map", "hourly", "0.9"),
    ("dashboard.html", "/dashboard", "hourly", "0.8"),
    ("insights.html", "/insights", "daily", "0.8"),
    ("research.html", "/research", "daily", "0.7"),
    ("news.html", "/news", "hourly", "0.7"),
    ("learn.html", "/learn", "monthly", "0.9"),
    ("guide/earthquake-basics.html", "/guide/earthquake-basics", "monthly", "0.8"),
    ("guide/plate-tectonics.html", "/guide/plate-tectonics", "monthly", "0.8"),
    ("guide/measuring-earthquakes.html", "/guide/measuring-earthquakes", "monthly", "0.8"),
    ("guide/magnitude-and-intensity.html", "/guide/magnitude-and-intensity", "monthly", "0.8"),
    ("guide/earthquake-hazards.html", "/guide/earthquake-hazards", "monthly", "0.8"),
    ("guide/notable-earthquakes.html", "/guide/notable-earthquakes", "monthly", "0.8"),
    ("guide/earthquake-glossary.html", "/guide/earthquake-glossary", "monthly", "0.8"),
    ("guide/earthquake-faq.html", "/guide/earthquake-faq", "monthly", "0.8"),
    ("guide/earthquake-safety.html", "/guide/earthquake-safety", "monthly", "0.8"),
    ("about.html", "/about", "monthly", "0.3"),
    ("privacy.html", "/privacy", "yearly", "0.2"),
    ("terms.html", "/terms", "yearly", "0.2"),
    ("app.html", "/app", "weekly", "0.6"),
    ("3d/index.html", "/3d/", "weekly", "0.5"),
]

# 그룹이 바뀌는 자리에 넣는 설명. 사이트맵을 읽는 사람을 위한 것.
GROUP_NOTES = {
    "/learn": "The Earthquake Guide: a hub and nine topics",
    "/about": "Policy pages, linked from the footer",
    "/app": "The console and the 3D globe are applications rather than documents;\n"
            "       they are listed so they can be found, at a lower priority.",
}

SITEMAP_NOTE = """<!--
  Clean URLs throughout. The host redirects /x.html to /x with a 308, so listing
  the .html form pointed every entry at a redirect rather than at the page.

  The nine /guide/ pages were one URL until now: the Earthquake Guide kept all
  ten topics on /learn with nine of them behind display:none tabs, which left
  about 44,000 characters of text with a single page to rank on. /learn is the
  hub the tiles already made it.

  Generated by scripts/build_seo.py -- edit the PAGES table there, not this file.
-->
"""

NL = chr(10)

# Crawlers that scrape pages to train models, as distinct from the ones that
# index for search or answer a question and link back. Search and agent bots
# stay welcome: being findable is the point. robots.txt is a request, not a
# control -- the enforcing block is configured at the edge.
TRAINING_BOTS = [
    "GPTBot",              # OpenAI, training
    "Google-Extended",     # Gemini training; does NOT affect Google Search
    "CCBot",               # Common Crawl
    "ClaudeBot",
    "anthropic-ai",
    "Applebot-Extended",   # Apple training opt-out; plain Applebot still indexes
    "meta-externalagent",
    "Bytespider",
]

ROBOTS = (f"""# World Earthquake Labs
User-agent: *
Allow: /

# The catalogue binaries are about 100 MB and hold nothing a crawler can read.
# (This pattern also covers the .part files they are split into.)
Disallow: /3d/data/*.bin

"""
    + "".join(f"User-agent: {bot}" + NL + "Disallow: /" + NL + NL for bot in TRAINING_BOTS)
    + f"Sitemap: {SITE}/sitemap.xml" + NL)


def last_commit(path: str) -> str:
    """git 이 아는 최종 수정 시각. 없으면 오늘."""
    out = subprocess.run(["git", "log", "-1", "--format=%cI", "--", path],
                         cwd=ROOT, capture_output=True, text=True)
    stamp = out.stdout.strip()
    if stamp:
        return stamp[:10]
    return datetime.now(timezone.utc).date().isoformat()


def main() -> int:
    (ROOT / "robots.txt").write_text(ROBOTS, encoding="utf-8", newline="\n")
    print("robots.txt")

    rows = []
    for name, path, freq, prio in PAGES:
        if not (ROOT / name).exists():
            print(f"  건너뜀(없음): {name}")
            continue
        note = GROUP_NOTES.get(path)
        rows.append(
            (f"\n  <!-- {note} -->\n" if note else "")
            + "  <url>\n"
            f"    <loc>{escape(SITE + path)}</loc>\n"
            f"    <lastmod>{last_commit(name)}</lastmod>\n"
            f"    <changefreq>{freq}</changefreq>\n"
            f"    <priority>{prio}</priority>\n"
            "  </url>")
        print(f"  {path}")

    sitemap = ('<?xml version="1.0" encoding="UTF-8"?>\n'
               + SITEMAP_NOTE
               + '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
               + "\n".join(rows) + "\n</urlset>\n")
    (ROOT / "sitemap.xml").write_text(sitemap, encoding="utf-8", newline="\n")
    print(f"sitemap.xml — {len(rows)}개")
    return 0


if __name__ == "__main__":
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    raise SystemExit(main())
